package work

import (
	"fmt"
	"os"
	"path/filepath"
)

func CreateProjectStructure(projectName, framework, db, sqlDriver string) error {
	base := projectName
	dirs := []string{
		filepath.Join(base, "cmd", "api"),
		filepath.Join(base, "cmd", "worker"),
		filepath.Join(base, "internal", "auth"),
		filepath.Join(base, "internal", "storage"),
		filepath.Join(base, "internal", "transport"),
		filepath.Join(base, "pkg", "logger"),
		filepath.Join(base, "pkg", "crypto"),
		filepath.Join(base, "api"),
		filepath.Join(base, "config"),
		filepath.Join(base, "scripts"),
	}

	// create directories
	for _, dir := range dirs {
		if err := os.MkdirAll(dir, 0o755); err != nil {
			return fmt.Errorf("failed to create %s: %w", dir, err)
		}
	}

	// create placeholder files
	files := map[string]string{
		filepath.Join(base, "cmd", "api", "main.go"):    fmt.Sprintf("// main.go for API server (%s)\npackage main", framework),
		filepath.Join(base, "cmd", "worker", "main.go"): "// main.go for Worker\npackage main",
		filepath.Join(base, "api", "openapi.yaml"):      "# OpenAPI spec",
		filepath.Join(base, "config", "config.yaml"):    "default: config",
		filepath.Join(base, "scripts", "deploy.sh"):     "#!/bin/bash\necho 'Deploy script'",
		filepath.Join(base, "go.mod"):                   fmt.Sprintf("module %s\n\ngo 1.21", projectName),
		filepath.Join(base, "README.md"):                fmt.Sprintf("# %s\nGenerated by GoStart", projectName),
	}

	for path, content := range files {
		if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
			return fmt.Errorf("failed to create file %s: %w", path, err)
		}
	}

	fmt.Println("✅ Project structure created successfully!")
	return nil
}
